/**
 * tools/_shared/_rag_common.js
 * RAG 模組共用常數、全域狀態、連線管理
 * 被 rag_index.js 和 rag_query.js 共同 import
 */

import fs from "fs/promises";
import path from "path";
import { resolveSecurePath, CONFIG } from "../../config.js";

// ============================================
// 設定常數
// ============================================
export const CHROMA_URL = "http://localhost:8010";
export const EMBEDDING_MODEL = "Xenova/paraphrase-multilingual-MiniLM-L12-v2";

export const SKIP_DIRS = new Set([
  "vendor", "node_modules", ".git", ".svn",
  "lib", "plugin", "plugins", "packages",
  "storage", "cache", ".idea", ".vscode", "__pycache__",
  "dist", "build", "out", ".next", ".nuxt",
  "uploads", "images", "webfonts", "screenshots",
  "axshare_screen_shot",
  "log", "logs",
]);

export const DEFAULT_EXTENSIONS = [
  ".php", ".js", ".ts", ".css", ".sql",
  ".md", ".json", ".html", ".vue", ".twig",
];

export const SKIP_FILE_PATTERNS = [
  /\.min\.(js|css)$/i,
  /\.bundle\.(js|css)$/i,
  /[-.]packed\.js$/i,
  /[-.]slim\.(js|css)$/i,
];

export const THIRD_PARTY_SIGNATURES = [
  /\bjQuery\s+(v|Foundation)/i,
  /\bBootstrap\s+v/i,
  /\blodash/i,
  /\bUnderscore\.js/i,
  /\bSelect2/i,
  /\bDataTable/i,
  /\bmoment\.js/i,
  /\bChart\.js/i,
  /\bvue\.js/i,
  /\breact/i,
  /\bangular/i,
  /\bFont Awesome/i,
  /\bAdminLTE/i,
  /\bSweetAlert/i,
  /\btoastr/i,
  /\bTinyMCE/i,
  /\bCKEditor/i,
  /\bslick carousel/i,
  /\bfancybox/i,
  /\blightbox/i,
  /\bgenerated\s+by\b/i,
  /\bauto[- ]generated\b/i,
  /\bDO NOT EDIT\b/,
  /\bThis file is automatically generated\b/i,
];

export const MINIFIED_LINE_THRESHOLD = 500;
export const MINIFIED_MAX_LINES = 5;
export const MAX_FILE_SIZE = 500 * 1024;
export const CHUNK_LINES = 60;
export const CHUNK_OVERLAP = 10;
export const EMBED_CONCURRENCY = 1;
export const EMBED_BATCH_SIZE = 20;
export const FILE_TIMEOUT_MS = 30_000;
export const PROGRESS_INTERVAL = 10;
export const AUTO_BATCH_LIMIT = 80;

// ============================================
// 全域狀態（Lazy-loaded）
// ============================================
export let chromaClient = null;
export let embeddingFn = null;

// ============================================
// ChromaDB 連線
// ============================================
export async function getChromaClient() {
  if (chromaClient) {
    try {
      await chromaClient.heartbeat();
      return chromaClient;
    } catch {
      chromaClient = null;
    }
  }

  try {
    const { ChromaClient } = await import("chromadb");
    const client = new ChromaClient({ host: "localhost", port: 8010 });
    await client.heartbeat();
    chromaClient = client;

    if (!embeddingFn) {
      const { DefaultEmbeddingFunction } = await import("@chroma-core/default-embed");
      embeddingFn = new DefaultEmbeddingFunction({ modelName: EMBEDDING_MODEL });
    }

    return client;
  } catch (err) {
    logProgress(`ChromaDB 連線失敗: ${err.message}`);
    return null;
  }
}

export async function getCollection(client, name, create = false) {
  const opts = { name, embeddingFunction: embeddingFn };
  return create
    ? client.getOrCreateCollection(opts)
    : client.getCollection(opts);
}

export function chromaUnavailable() {
  return {
    isError: true,
    content: [
      {
        type: "text",
        text:
          "⚠️ ChromaDB 未連線（RAG 為選用功能，不影響其他工具）。\n" +
          "啟動方式：\n" +
          "  cd D:\\MCP_Server\\chromadb && docker compose up -d\n" +
          "確認連線：http://localhost:8010/api/v2/heartbeat",
      },
    ],
  };
}

// ============================================
// 工具函式
// ============================================
export function logProgress(msg) {
  console.error(`[rag] ${msg}`);
}

export async function scanFiles(dirPath, extensions) {
  const results = [];

  async function walk(dir) {
    let entries;
    try {
      entries = await fs.readdir(dir, { withFileTypes: true });
    } catch {
      return;
    }

    for (const entry of entries) {
      const fullPath = path.join(dir, entry.name);

      if (entry.isDirectory()) {
        if (!SKIP_DIRS.has(entry.name)) {
          await walk(fullPath);
        }
      } else if (entry.isFile()) {
        const ext = path.extname(entry.name).toLowerCase();
        if (extensions.includes(ext)) {
          if (SKIP_FILE_PATTERNS.some((re) => re.test(entry.name))) continue;
          try {
            const stat = await fs.stat(fullPath);
            if (stat.size <= MAX_FILE_SIZE) {
              results.push({ fullPath, size: stat.size, mtime: stat.mtimeMs });
            }
          } catch {
            // skip
          }
        }
      }
    }
  }

  await walk(dirPath);
  return results;
}

export function chunkFile(content, relPath, chunkLinesCount = CHUNK_LINES, chunkOverlap = CHUNK_OVERLAP) {
  const lines = content.split(/\r?\n/);
  const chunks = [];
  const funcDefs = detectPhpFunctions(lines);

  if (lines.length <= chunkLinesCount) {
    const meta = buildChunkMeta(relPath, 1, lines.length, funcDefs);
    chunks.push({
      text: content,
      startLine: 1,
      endLine: lines.length,
      ...meta,
    });
    return chunks;
  }

  let start = 0;
  while (start < lines.length) {
    let end = Math.min(start + chunkLinesCount, lines.length);

    if (end < lines.length) {
      const searchLimit = Math.min(end + 10, lines.length);
      for (let i = end; i < searchLimit; i++) {
        const line = lines[i].trim();
        if (line === "" || line === "}" || line === "};") {
          end = i + 1;
          break;
        }
      }
    }

    const slicedLines = lines.slice(start, end);
    const meta = buildChunkMeta(relPath, start + 1, end, funcDefs);
    chunks.push({
      text: slicedLines.join("\n"),
      startLine: start + 1,
      endLine: end,
      ...meta,
    });

    start = end - chunkOverlap;
    if (start <= chunks[chunks.length - 1].startLine - 1) {
      start = end;
    }
  }

  return chunks;
}

export function detectPhpFunctions(lines) {
  let className = "";
  const funcs = [];

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    const classMatch = line.match(/^\s*(?:abstract\s+)?class\s+(\w+)/);
    if (classMatch) className = classMatch[1];

    const funcMatch = line.match(/^\s*(?:public|protected|private)?\s*(?:static\s+)?function\s+(\w+)\s*\(/);
    if (funcMatch) {
      funcs.push({ name: funcMatch[1], startLine: i + 1 });
    }
  }

  return { className, funcs };
}

export function buildChunkMeta(relPath, startLine, endLine, funcDefs) {
  const meta = {};

  if (funcDefs.className) {
    meta.class_name = funcDefs.className;
  }

  const containedFuncs = funcDefs.funcs
    .filter(f => f.startLine >= startLine && f.startLine <= endLine)
    .map(f => f.name);

  if (containedFuncs.length > 0) {
    meta.methods = containedFuncs.join(",");
  }

  const rp = relPath.replace(/\\/g, "/").toLowerCase();
  if (rp.includes("admincontrol") || rp.includes("/admin/")) {
    meta.file_type = "admin";
  } else if (rp.includes("cls/model") || rp.includes(".class.php")) {
    meta.file_type = "model";
  } else if (rp.includes("/ajax/") || rp.includes("_ajax")) {
    meta.file_type = "ajax";
  } else if (rp.includes("/js/") || rp.endsWith(".js")) {
    meta.file_type = "js";
  }

  return meta;
}

export function getRelPath(fullPath) {
  const base = CONFIG.basePath.replace(/\\/g, "/").replace(/\/$/, "");
  const full = fullPath.replace(/\\/g, "/");
  return full.startsWith(base + "/") ? full.slice(base.length + 1) : full;
}

export function detectLanguage(filePath) {
  const ext = path.extname(filePath).slice(1).toLowerCase();
  const map = {
    php: "php", js: "javascript", ts: "typescript", jsx: "javascript",
    tsx: "typescript", css: "css", html: "html", vue: "vue",
    sql: "sql", json: "json", md: "markdown", twig: "twig",
  };
  return map[ext] || ext;
}

export async function runWithConcurrency(tasks, concurrency) {
  const results = [];
  let index = 0;

  async function worker() {
    while (index < tasks.length) {
      const i = index++;
      results[i] = await tasks[i]();
    }
  }

  const workers = Array.from(
    { length: Math.min(concurrency, tasks.length) },
    () => worker()
  );
  await Promise.all(workers);
  return results;
}

export function withTimeout(promise, ms, label) {
  return Promise.race([
    promise,
    new Promise((_, reject) =>
      setTimeout(() => reject(new Error(`Timeout after ${ms}ms: ${label}`)), ms)
    ),
  ]);
}
