/**
 * tools/rag.js — RAG 向量檢索工具（ChromaDB）
 *
 * 選用功能：ChromaDB 未啟動時，其他 MCP 工具完全不受影響。
 * 啟動方式：cd chromadb && docker compose up -d
 */

import fs from "fs/promises";
import path from "path";
import { resolveSecurePath, CONFIG } from "../config.js";

// ============================================
// 設定常數
// ============================================
const CHROMA_URL = "http://localhost:8010";
// Client-side embedding（ChromaDB 1.0.0 不支援 server-side）
// 首次載入 ONNX 模型 ~470MB，之後走快取
const EMBEDDING_MODEL = "Xenova/paraphrase-multilingual-MiniLM-L12-v2";

const SKIP_DIRS = new Set([
  // 套件 / 第三方
  "vendor", "node_modules", ".git", ".svn",
  "lib", "plugin", "plugins", "packages",
  // IDE / 快取
  "storage", "cache", ".idea", ".vscode", "__pycache__",
  // 編譯 / 產出
  "dist", "build", "out", ".next", ".nuxt",
  // 媒體 / 上傳 / 靜態資源（非程式碼）
  "uploads", "images", "webfonts", "screenshots",
  "axshare_screen_shot",
  // 日誌
  "log", "logs",
]);

const DEFAULT_EXTENSIONS = [
  ".php", ".js", ".ts", ".css", ".sql",
  ".md", ".json", ".html", ".vue", ".twig",
];

// 檔名層級：跳過壓縮/打包檔
const SKIP_FILE_PATTERNS = [
  /\.min\.(js|css)$/i,
  /\.bundle\.(js|css)$/i,
  /[-.]packed\.js$/i,
  /[-.]slim\.(js|css)$/i,
];

// 內容層級：前 5 行出現這些關鍵字 → 第三方
const THIRD_PARTY_SIGNATURES = [
  /\bjQuery\s+(v|Foundation)/i,
  /\bBootstrap\s+v/i,
  /\blodash/i,
  /\bUnderscore\.js/i,
  /\bSelect2/i,
  /\bDataTable/i,
  /\bmoment\.js/i,
  /\bChart\.js/i,
  /\bvue\.js/i,
  /\breact/i,
  /\bangular/i,
  /\bFont Awesome/i,
  /\bAdminLTE/i,
  /\bSweetAlert/i,
  /\btoastr/i,
  /\bTinyMCE/i,
  /\bCKEditor/i,
  /\bslick carousel/i,
  /\bfancybox/i,
  /\blightbox/i,
  /\bgenerated\s+by\b/i,
  /\bauto[- ]generated\b/i,
  /\bDO NOT EDIT\b/,
  /\bThis file is automatically generated\b/i,
];

// 壓縮偵測：單行超長 + 行數極少 → minified
const MINIFIED_LINE_THRESHOLD = 500;  // 單行字元數
const MINIFIED_MAX_LINES = 5;         // 總行數上限

const MAX_FILE_SIZE = 500 * 1024; // 500KB
const CHUNK_LINES = 60;
const CHUNK_OVERLAP = 10;
const EMBED_CONCURRENCY = 1;        // 逐檔處理，降低 RAM 峰值（16GB 環境）
const EMBED_BATCH_SIZE = 20;         // 每批送 ChromaDB 的 chunk 數
const FILE_TIMEOUT_MS = 30_000;      // 單檔處理 timeout (30s)
const PROGRESS_INTERVAL = 10;        // 每處理 N 個檔案回報一次進度
const AUTO_BATCH_LIMIT = 80;         // 超過此數量自動分批，防止記憶體溢出

// Lazy-loaded ChromaDB client & embedding function
let chromaClient = null;
let embeddingFn = null;

// ============================================
// 工具定義
// ============================================
export const definitions = [
  {
    name: "rag_index",
    description:
      "將專案檔案索引至 ChromaDB 向量資料庫，支援增量索引（僅處理變更檔案）。" +
      "需先啟動 ChromaDB Docker 容器。",
    inputSchema: {
      type: "object",
      properties: {
        project: {
          type: "string",
          description:
            "專案資料夾名稱（如 PG_dbox3），自動建立 collection rag_{project}",
        },
        paths: {
          type: "array",
          items: { type: "string" },
          description:
            "要索引的檔案或目錄路徑陣列（相對 basePath）。目錄會遞迴掃描",
        },
        shared: {
          type: "boolean",
          description:
            "設為 true 寫入 rag_shared collection（跨專案共用知識）",
        },
        force: {
          type: "boolean",
          description: "強制重新索引所有檔案（忽略 mtime 檢查）",
        },
        extensions: {
          type: "array",
          items: { type: "string" },
          description:
            "要索引的副檔名（預設 .php,.js,.ts,.css,.sql,.md,.json,.html,.vue,.twig）",
        },
        chunk_lines: {
          type: "integer",
          description: "每個 chunk 的行數(預設 60)",
        },
        chunk_overlap: {
          type: "integer",
          description: "chunk 之間的重疊行數(預設 10)",
        },
      },
      required: ["project", "paths"],
    },
  },
  {
    name: "rag_query",
    description:
      "語意搜尋已索引的程式碼（從 ChromaDB 向量檢索最相關的片段）",
    inputSchema: {
      type: "object",
      properties: {
        project: {
          type: "string",
          description: "專案資料夾名稱（查詢 rag_{project} collection）",
        },
        query: {
          type: "string",
          description:
            "自然語言查詢（如「使用者登入驗證邏輯」「PDF 匯出功能」）",
        },
        n_results: {
          type: "integer",
          description: "回傳結果數量（預設 5，最多 20）",
        },
        include_shared: {
          type: "boolean",
          description: "同時查詢 rag_shared collection（預設 false）",
        },
        filter_path: {
          type: "string",
          description: "限定檔案路徑前綴（如 admin/order/ 只搜尋該目錄）",
        },
        filter_language: {
          type: "string",
          description: "限定程式語言（如 php、js）",
        },
        filter_class: {
          type: "string",
          description: "限定 PHP class 名稱（精確匹配，如 order、news）",
        },
        filter_file_type: {
          type: "string",
          enum: ["model", "admin", "ajax", "js"],
          description: "限定檔案類型（model=cls/model, admin=adminControl, ajax=AJAX, js=JavaScript）",
        },
      },
      required: ["project", "query"],
    },
  },
  {
    name: "rag_status",
    description:
      "查看 RAG 索引狀態（ChromaDB 連線、collection 統計、已索引檔案清單）",
    inputSchema: {
      type: "object",
      properties: {
        project: {
          type: "string",
          description:
            "專案名稱（查看特定 collection，不填則列出所有 collections）",
        },
      },
    },
  },
  {
    name: "rag_query_batch",
    description:
      "批次語意搜尋（一次送多個查詢，共用 embedding 載入，比逐次 rag_query 更高效）",
    inputSchema: {
      type: "object",
      properties: {
        project: {
          type: "string",
          description: "專案資料夾名稱（查詢 rag_{project} collection）",
        },
        queries: {
          type: "array",
          items: { type: "string" },
          description: "多個自然語言查詢陣列",
        },
        n_results: {
          type: "integer",
          description: "每個查詢的回傳結果數量（預設 3，最多 10）",
        },
        filter_path: {
          type: "string",
          description: "限定檔案路徑前綴（所有查詢共用）",
        },
        filter_language: {
          type: "string",
          description: "限定程式語言（所有查詢共用）",
        },
        filter_class: {
          type: "string",
          description: "限定 PHP class 名稱（所有查詢共用）",
        },
        filter_file_type: {
          type: "string",
          enum: ["model", "admin", "ajax", "js"],
          description: "限定檔案類型（所有查詢共用）",
        },
      },
      required: ["project", "queries"],
    },
  },
];

// ============================================
// ChromaDB 連線（Lazy + Graceful）
// ============================================
async function getChromaClient() {
  if (chromaClient) {
    try {
      await chromaClient.heartbeat();
      return chromaClient;
    } catch {
      chromaClient = null;
    }
  }

  try {
    const { ChromaClient } = await import("chromadb");
    const client = new ChromaClient({ host: "localhost", port: 8010 });
    await client.heartbeat();
    chromaClient = client;

    // 初始化多語言 Embedding Function（首次載入模型較慢，之後走快取）
    if (!embeddingFn) {
      const { DefaultEmbeddingFunction } = await import("@chroma-core/default-embed");
      embeddingFn = new DefaultEmbeddingFunction({ modelName: EMBEDDING_MODEL });
    }

    return client;
  } catch (err) {
    logProgress(`ChromaDB 連線失敗: ${err.message}`);
    return null;
  }
}

/** 取得或建立 collection（統一使用多語言 Embedding） */
async function getCollection(client, name, create = false) {
  const opts = { name, embeddingFunction: embeddingFn };
  return create
    ? client.getOrCreateCollection(opts)
    : client.getCollection(opts);
}

function chromaUnavailable() {
  return {
    isError: true,
    content: [
      {
        type: "text",
        text:
          "⚠️ ChromaDB 未連線（RAG 為選用功能，不影響其他工具）。\n" +
          "啟動方式：\n" +
          "  cd D:\\MCP_Server\\chromadb && docker compose up -d\n" +
          "確認連線：http://localhost:8010/api/v2/heartbeat",
      },
    ],
  };
}

// ============================================
// 進度回報（stderr，不干擾 MCP stdout）
// ============================================
function logProgress(msg) {
  console.error(`[rag] ${msg}`);
}

// ============================================
// 檔案掃描
// ============================================
async function scanFiles(dirPath, extensions) {
  const results = [];

  async function walk(dir) {
    let entries;
    try {
      entries = await fs.readdir(dir, { withFileTypes: true });
    } catch {
      return;
    }

    for (const entry of entries) {
      const fullPath = path.join(dir, entry.name);

      if (entry.isDirectory()) {
        if (!SKIP_DIRS.has(entry.name)) {
          await walk(fullPath);
        }
      } else if (entry.isFile()) {
        const ext = path.extname(entry.name).toLowerCase();
        if (extensions.includes(ext)) {
          // 檔名層級過濾：.min.js, .bundle.css 等
          if (SKIP_FILE_PATTERNS.some((re) => re.test(entry.name))) continue;
          try {
            const stat = await fs.stat(fullPath);
            if (stat.size <= MAX_FILE_SIZE) {
              results.push({ fullPath, size: stat.size, mtime: stat.mtimeMs });
            }
          } catch {
            // skip unreadable files
          }
        }
      }
    }
  }

  await walk(dirPath);
  return results;
}

// ============================================
// 切片（Chunking）
// ============================================
function chunkFile(content, relPath, chunkLinesCount = CHUNK_LINES, chunkOverlap = CHUNK_OVERLAP) {
  const lines = content.split(/\r?\n/);
  const chunks = [];

  // 偵測 PHP function 定義位置（用於 function-level metadata）
  const funcDefs = detectPhpFunctions(lines);

  if (lines.length <= chunkLinesCount) {
    // 小檔案不切片
    const meta = buildChunkMeta(relPath, 1, lines.length, funcDefs);
    chunks.push({
      text: content,
      startLine: 1,
      endLine: lines.length,
      ...meta,
    });
    return chunks;
  }

  let start = 0;
  while (start < lines.length) {
    let end = Math.min(start + chunkLinesCount, lines.length);

    // 智慧邊界：如果切到函式中間，往後找空行或頂層 }
    if (end < lines.length) {
      const searchLimit = Math.min(end + 10, lines.length);
      for (let i = end; i < searchLimit; i++) {
        const line = lines[i].trim();
        if (line === "" || line === "}" || line === "};") {
          end = i + 1;
          break;
        }
      }
    }

    const slicedLines = lines.slice(start, end);
    const meta = buildChunkMeta(relPath, start + 1, end, funcDefs);
    chunks.push({
      text: slicedLines.join("\n"),
      startLine: start + 1,
      endLine: end,
      ...meta,
    });

    // 下一個 chunk 起始點（含重疊）
    start = end - chunkOverlap;
    if (start <= chunks[chunks.length - 1].startLine - 1) {
      start = end; // 防止無限迴圈
    }
  }

  return chunks;
}

/** 偵測 PHP 檔案中的 class 名稱和 function 定義（行號範圍） */
function detectPhpFunctions(lines) {
  let className = "";
  const funcs = []; // { name, startLine (1-based) }

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    const classMatch = line.match(/^\s*(?:abstract\s+)?class\s+(\w+)/);
    if (classMatch) className = classMatch[1];

    const funcMatch = line.match(/^\s*(?:public|protected|private)?\s*(?:static\s+)?function\s+(\w+)\s*\(/);
    if (funcMatch) {
      funcs.push({ name: funcMatch[1], startLine: i + 1 });
    }
  }

  return { className, funcs };
}

/** 為 chunk 附加 function-level metadata */
function buildChunkMeta(relPath, startLine, endLine, funcDefs) {
  const meta = {};

  // class name
  if (funcDefs.className) {
    meta.class_name = funcDefs.className;
  }

  // 找出此 chunk 包含的 function 名稱
  const containedFuncs = funcDefs.funcs
    .filter(f => f.startLine >= startLine && f.startLine <= endLine)
    .map(f => f.name);

  if (containedFuncs.length > 0) {
    meta.methods = containedFuncs.join(",");
  }

  // 檔案類型推斷（admin/model/ajax/frontend）
  const rp = relPath.replace(/\\/g, "/").toLowerCase();
  if (rp.includes("admincontrol") || rp.includes("/admin/")) {
    meta.file_type = "admin";
  } else if (rp.includes("cls/model") || rp.includes(".class.php")) {
    meta.file_type = "model";
  } else if (rp.includes("/ajax/") || rp.includes("_ajax")) {
    meta.file_type = "ajax";
  } else if (rp.includes("/js/") || rp.endsWith(".js")) {
    meta.file_type = "js";
  }

  return meta;
}

/** 取得相對於 basePath 的路徑 */
function getRelPath(fullPath) {
  const base = CONFIG.basePath.replace(/\\/g, "/").replace(/\/$/, "");
  const full = fullPath.replace(/\\/g, "/");
  return full.startsWith(base + "/") ? full.slice(base.length + 1) : full;
}

/** 從副檔名推斷語言 */
function detectLanguage(filePath) {
  const ext = path.extname(filePath).slice(1).toLowerCase();
  const map = {
    php: "php", js: "javascript", ts: "typescript", jsx: "javascript",
    tsx: "typescript", css: "css", html: "html", vue: "vue",
    sql: "sql", json: "json", md: "markdown", twig: "twig",
  };
  return map[ext] || ext;
}

// ============================================
// 並行控制
// ============================================
async function runWithConcurrency(tasks, concurrency) {
  const results = [];
  let index = 0;

  async function worker() {
    while (index < tasks.length) {
      const i = index++;
      results[i] = await tasks[i]();
    }
  }

  const workers = Array.from(
    { length: Math.min(concurrency, tasks.length) },
    () => worker()
  );
  await Promise.all(workers);
  return results;
}

/** 帶 timeout 的 Promise */
function withTimeout(promise, ms, label) {
  return Promise.race([
    promise,
    new Promise((_, reject) =>
      setTimeout(() => reject(new Error(`Timeout after ${ms}ms: ${label}`)), ms)
    ),
  ]);
}

// ============================================
// 工具邏輯
// ============================================
export async function handle(name, args) {
  const client = await getChromaClient();
  if (!client) return chromaUnavailable();

  if (name === "rag_index") return await handleIndex(client, args);
  if (name === "rag_query") return await handleQuery(client, args);
  if (name === "rag_query_batch") return await handleQueryBatch(client, args);
  if (name === "rag_status") return await handleStatus(client, args);
}

// ── rag_index ──────────────────────────────────
async function handleIndex(client, args) {
  const collectionName = args.shared
    ? "rag_shared"
    : `rag_${args.project}`;
  const extensions = (args.extensions || DEFAULT_EXTENSIONS).map((e) =>
    e.startsWith(".") ? e : `.${e}`
  );
  const force = args.force || false;
  const chunkLines = args.chunk_lines || CHUNK_LINES;
  const chunkOverlap = args.chunk_overlap || CHUNK_OVERLAP;

  const collection = await getCollection(client, collectionName, true);

  // ── 0. 預熱 Embedding 模型（首次載入 ONNX ~30-60s，避免 FILE_TIMEOUT 誤殺） ──
  if (embeddingFn) {
    logProgress(`預熱 Embedding 模型中（首次載入較慢）...`);
    try {
      await embeddingFn.generate(["warmup"]);
      logProgress(`Embedding 模型就緒`);
    } catch (err) {
      logProgress(`Embedding 預熱失敗: ${err.message}`);
      return {
        isError: true,
        content: [{ type: "text", text: `❌ Embedding 模型載入失敗: ${err.message}\n請確認 @chroma-core/default-embed 已安裝且 ONNX 模型快取完整。` }],
      };
    }
  }

  // ── 1. 收集所有目標檔案 ──
  logProgress(`掃描檔案中...`);
  let allFiles = [];
  for (const p of args.paths) {
    const fullPath = resolveSecurePath(p);
    const stat = await fs.stat(fullPath);

    if (stat.isDirectory()) {
      const files = await scanFiles(fullPath, extensions);
      allFiles.push(...files);
    } else if (stat.isFile()) {
      allFiles.push({ fullPath, size: stat.size, mtime: stat.mtimeMs });
    }
  }
  logProgress(`找到 ${allFiles.length} 個檔案`);

  // ── 2. 批次增量檢查（一次拉所有已索引檔案的 metadata） ──
  let indexedFileMap = new Map(); // relPath → latest indexed_at
  if (!force) {
    logProgress(`載入已索引檔案清單...`);
    try {
      // 分批拉取（ChromaDB get limit）
      const PAGE_SIZE = 5000;
      let offset = 0;
      let hasMore = true;
      while (hasMore) {
        const batch = await collection.get({
          limit: PAGE_SIZE,
          offset,
          include: ["metadatas"],
        });
        if (!batch.ids || batch.ids.length === 0) {
          hasMore = false;
          break;
        }
        for (const m of batch.metadatas) {
          const existing = indexedFileMap.get(m.file_path);
          if (!existing || m.indexed_at > existing) {
            indexedFileMap.set(m.file_path, m.indexed_at);
          }
        }
        offset += batch.ids.length;
        if (batch.ids.length < PAGE_SIZE) hasMore = false;
      }
      logProgress(`已索引檔案: ${indexedFileMap.size} 個`);
    } catch {
      // collection 可能為空
      logProgress(`Collection 為空或無法讀取，將索引所有檔案`);
    }
  }

  // ── 3. 過濾需要處理的檔案 ──
  const filesToProcess = [];
  let skipped = 0;
  for (const file of allFiles) {
    const relPath = getRelPath(file.fullPath);
    if (!force) {
      const lastIndexed = indexedFileMap.get(relPath);
      if (lastIndexed && new Date(lastIndexed).getTime() >= file.mtime) {
        skipped++;
        continue;
      }
    }
    filesToProcess.push({ ...file, relPath });
  }
  logProgress(`需處理: ${filesToProcess.length} | 跳過(未變更): ${skipped}`);

  if (filesToProcess.length === 0) {
    return {
      content: [{
        type: "text",
        text: `✅ 索引已是最新 → collection: ${collectionName}\n` +
              `   檔案總數: ${allFiles.length} | 全部跳過（無變更）`,
      }],
    };
  }

  // ── 4. 自動分批處理（防止記憶體溢出） ──
  const totalBatches = Math.ceil(filesToProcess.length / AUTO_BATCH_LIMIT);
  if (totalBatches > 1) {
    logProgress(`檔案數 ${filesToProcess.length} → 自動分 ${totalBatches} 批（每批 ${AUTO_BATCH_LIMIT}）`);
  }

  let indexed = 0;
  let chunksCreated = 0;
  let skippedThirdParty = 0;
  const errors = [];
  const startTime = Date.now();

  for (let batchIdx = 0; batchIdx < totalBatches; batchIdx++) {
    const batchFiles = filesToProcess.slice(
      batchIdx * AUTO_BATCH_LIMIT,
      (batchIdx + 1) * AUTO_BATCH_LIMIT
    );
    if (totalBatches > 1) {
      logProgress(`── 批次 ${batchIdx + 1}/${totalBatches}（${batchFiles.length} 檔）──`);
    }

    const tasks = batchFiles.map((file) => async () => {
      try {
        const result = await withTimeout(
          processFile(collection, file, args.project, chunkLines, chunkOverlap),
          FILE_TIMEOUT_MS,
          file.relPath
        );
        if (result.skipped) {
          skippedThirdParty++;
          logProgress(`⊘ 第三方跳過: ${file.relPath} (${result.reason})`);
        } else {
          indexed++;
          chunksCreated += result.chunks;
        }

        // 進度回報
        const done = indexed + skippedThirdParty + errors.length;
        if (done % PROGRESS_INTERVAL === 0 || done === filesToProcess.length) {
          const elapsed = ((Date.now() - startTime) / 1000).toFixed(1);
          const rate = (done / (Date.now() - startTime) * 1000).toFixed(1);
          logProgress(
            `[${done}/${filesToProcess.length}] ${elapsed}s elapsed, ` +
            `${rate} files/s, ${chunksCreated} chunks`
          );
        }
      } catch (err) {
        errors.push(`${file.relPath}: ${err.message}`);
        const done = indexed + skippedThirdParty + errors.length;
        if (done % PROGRESS_INTERVAL === 0) {
          logProgress(`[${done}/${filesToProcess.length}] (${errors.length} errors)`);
        }
      }
    });

    await runWithConcurrency(tasks, EMBED_CONCURRENCY);

    // 批次間暫停，讓 GC 有機會釋放記憶體
    if (totalBatches > 1 && batchIdx < totalBatches - 1) {
      if (global.gc) {
        global.gc();
        logProgress(`GC 完成`);
      }
      await new Promise((r) => setTimeout(r, 2000));
      logProgress(`批次 ${batchIdx + 1} 完成，等待 2s 後繼續...`);
    }
  }

  const elapsed = ((Date.now() - startTime) / 1000).toFixed(1);
  const lines = [
    `✅ 索引完成 → collection: ${collectionName}`,
    `   掃描: ${allFiles.length} 檔` + (totalBatches > 1 ? ` → ${totalBatches} 批自動分批` : ``),
    `   檔案索引: ${indexed} | 跳過(未變更): ${skipped} | 跳過(第三方): ${skippedThirdParty} | 切片: ${chunksCreated}`,
    `   耗時: ${elapsed}s`,
  ];
  if (errors.length > 0) {
    lines.push(`   ❌ 錯誤 (${errors.length}):`);
    errors.slice(0, 10).forEach((e) => lines.push(`      ${e}`));
    if (errors.length > 10) lines.push(`      ...及其他 ${errors.length - 10} 個`);
  }

  return { content: [{ type: "text", text: lines.join("\n") }] };
}

/** 偵測第三方 / minified 檔案 */
function isThirdParty(content) {
  // 1. 內容特徵：前 5 行比對已知套件簽名
  const headLines = content.split(/\r?\n/, 5);
  const head = headLines.join("\n");
  if (THIRD_PARTY_SIGNATURES.some((re) => re.test(head))) {
    return `signature match in header`;
  }

  // 2. 壓縮偵測：極少行但單行超長 → minified
  const lines = content.split(/\r?\n/);
  if (lines.length <= MINIFIED_MAX_LINES) {
    const maxLen = Math.max(...lines.map((l) => l.length));
    if (maxLen > MINIFIED_LINE_THRESHOLD) {
      return `minified (${lines.length} lines, longest ${maxLen} chars)`;
    }
  }

  return null; // 不是第三方
}

/** 處理單一檔案：讀取 → 切片 → 刪舊 → 批次寫入 */
async function processFile(collection, file, project, chunkLinesCount = CHUNK_LINES, chunkOverlap = CHUNK_OVERLAP) {
  const { fullPath, relPath, size } = file;
  const content = await fs.readFile(fullPath, "utf-8");

  // 第三方 / minified 偵測 → 跳過並清除舊 chunks
  const thirdPartyReason = isThirdParty(content);
  if (thirdPartyReason) {
    try { await collection.delete({ where: { file_path: relPath } }); } catch {}
    return { chunks: 0, skipped: true, reason: thirdPartyReason };
  }

  const chunks = chunkFile(content, relPath, chunkLinesCount, chunkOverlap);
  const language = detectLanguage(fullPath);
  const now = new Date().toISOString();

  // 刪除該檔案的舊 chunks
  try {
    await collection.delete({ where: { file_path: relPath } });
  } catch {
    // collection 可能為空，忽略
  }

  // 批次插入新 chunks
  for (let i = 0; i < chunks.length; i += EMBED_BATCH_SIZE) {
    const batch = chunks.slice(i, i + EMBED_BATCH_SIZE);
    await collection.add({
      ids: batch.map((c) => `${relPath}:${c.startLine}-${c.endLine}`),
      documents: batch.map((c) => c.text),
      metadatas: batch.map((c) => ({
        project,
        file_path: relPath,
        start_line: c.startLine,
        end_line: c.endLine,
        language,
        file_size: size,
        indexed_at: now,
        ...(c.class_name ? { class_name: c.class_name } : {}),
        ...(c.methods ? { methods: c.methods } : {}),
        ...(c.file_type ? { file_type: c.file_type } : {}),
      })),
    });
  }

  return { chunks: chunks.length };
}

// ── rag_query ──────────────────────────────────
async function handleQuery(client, args) {
  const nResults = Math.min(args.n_results || 5, 20);
  const collectionName = `rag_${args.project}`;

  // 預熱 Embedding（首次查詢時載入模型）
  if (embeddingFn) {
    try { await embeddingFn.generate(["warmup"]); } catch { /* ignore */ }
  }

  // 構建 where 過濾條件
  const whereConditions = [];
  if (args.filter_language) whereConditions.push({ language: args.filter_language });
  if (args.filter_class) whereConditions.push({ class_name: args.filter_class });
  if (args.filter_file_type) whereConditions.push({ file_type: args.filter_file_type });

  const where = whereConditions.length > 1
    ? { $and: whereConditions }
    : whereConditions.length === 1
      ? whereConditions[0]
      : undefined;

  // 多取一些結果以供 post-filter 路徑篩選
  const fetchCount = args.filter_path ? nResults * 3 : nResults;

  // 查詢專案 collection
  let results = [];
  try {
    const collection = await getCollection(client, collectionName);
    const res = await collection.query({
      queryTexts: [args.query],
      nResults: fetchCount,
      where,
      include: ["documents", "metadatas", "distances"],
    });

    if (res.ids[0]) {
      for (let i = 0; i < res.ids[0].length; i++) {
        const meta = res.metadatas[0][i];
        // post-filter: 路徑前綴篩選
        if (args.filter_path && !meta.file_path.includes(args.filter_path)) {
          continue;
        }
        results.push({
          id: res.ids[0][i],
          text: res.documents[0][i],
          metadata: meta,
          distance: res.distances[0][i],
          source: "project",
        });
      }
    }
  } catch (err) {
    if (err.message?.includes("does not exist")) {
      return {
        content: [
          {
            type: "text",
            text:
              `⚠️ Collection ${collectionName} 不存在。\n` +
              `請先執行 rag_index 建立索引：\n` +
              `  rag_index { project: "${args.project}", paths: ["${args.project}/"] }`,
          },
        ],
      };
    }
    throw err;
  }

  // 查詢 shared collection
  if (args.include_shared) {
    try {
      const sharedCol = await getCollection(client, "rag_shared");
      const res = await sharedCol.query({
        queryTexts: [args.query],
        nResults: Math.ceil(nResults / 2),
        include: ["documents", "metadatas", "distances"],
      });

      if (res.ids[0]) {
        for (let i = 0; i < res.ids[0].length; i++) {
          results.push({
            id: res.ids[0][i],
            text: res.documents[0][i],
            metadata: res.metadatas[0][i],
            distance: res.distances[0][i],
            source: "shared",
          });
        }
      }
    } catch {
      // rag_shared 不存在就跳過
    }
  }

  // 依 distance 排序（越小越相關）
  results.sort((a, b) => a.distance - b.distance);
  results = results.slice(0, nResults);

  if (results.length === 0) {
    return {
      content: [{ type: "text", text: "找不到相關結果。試試不同的查詢詞或先建立索引。" }],
    };
  }

  // 格式化輸出
  const parts = results.map((r, i) => {
    const m = r.metadata;
    const score = (1 - r.distance).toFixed(3);
    const tag = r.source === "shared" ? " [shared]" : "";
    const header =
      `── #${i + 1}${tag} | ${m.file_path}:${m.start_line}-${m.end_line} | ` +
      `相關度: ${score} | ${m.language}`;

    // 截斷過長的片段
    const maxChars = 2000;
    let text = r.text;
    if (text.length > maxChars) {
      text = text.slice(0, maxChars) + "\n... (截斷)";
    }

    return `${header}\n${text}`;
  });

  const header = `🔍 查詢: "${args.query}" → ${results.length} 個結果\n`;

  // 低信心度警告
  const bestDistance = results.length > 0 ? results[0].distance : 1;
  const lowConfidence = bestDistance > 0.45;
  const warning = lowConfidence
    ? `\n⚠️ 最佳結果 distance=${bestDistance.toFixed(3)}，語意搜尋信心度低。建議改用 Grep 精確搜尋或 class_method_lookup 直接定位。\n`
    : "";

  return { content: [{ type: "text", text: header + warning + parts.join("\n\n") }] };
}

// ── rag_query_batch ────────────────────────────
async function handleQueryBatch(client, args) {
  const nResults = Math.min(args.n_results || 3, 10);
  const collectionName = `rag_${args.project}`;

  // 預熱 Embedding（只做一次，所有查詢共用）
  if (embeddingFn) {
    try { await embeddingFn.generate(["warmup"]); } catch { /* ignore */ }
  }

  // 構建 where 過濾條件
  const batchWhereConditions = [];
  if (args.filter_language) batchWhereConditions.push({ language: args.filter_language });
  if (args.filter_class) batchWhereConditions.push({ class_name: args.filter_class });
  if (args.filter_file_type) batchWhereConditions.push({ file_type: args.filter_file_type });

  const where = batchWhereConditions.length > 1
    ? { $and: batchWhereConditions }
    : batchWhereConditions.length === 1
      ? batchWhereConditions[0]
      : undefined;
  const fetchCount = args.filter_path ? nResults * 3 : nResults;

  let collection;
  try {
    collection = await getCollection(client, collectionName);
  } catch (err) {
    if (err.message?.includes("does not exist")) {
      return {
        content: [{
          type: "text",
          text: `⚠️ Collection ${collectionName} 不存在。請先執行 rag_index。`,
        }],
      };
    }
    throw err;
  }

  const allParts = [];
  let hasLowConfidence = false;
  for (let qi = 0; qi < args.queries.length; qi++) {
    const query = args.queries[qi];
    let results = [];

    try {
      const res = await collection.query({
        queryTexts: [query],
        nResults: fetchCount,
        where,
        include: ["documents", "metadatas", "distances"],
      });

      if (res.ids[0]) {
        for (let i = 0; i < res.ids[0].length; i++) {
          const meta = res.metadatas[0][i];
          if (args.filter_path && !meta.file_path.includes(args.filter_path)) continue;
          results.push({
            text: res.documents[0][i],
            metadata: meta,
            distance: res.distances[0][i],
          });
        }
      }
    } catch {
      allParts.push(`── Q${qi + 1}: "${query}" → ❌ 查詢失敗`);
      continue;
    }

    results.sort((a, b) => a.distance - b.distance);
    results = results.slice(0, nResults);

    if (results.length === 0) {
      allParts.push(`── Q${qi + 1}: "${query}" → 無結果`);
      continue;
    }

    // 檢查信心度
    if (results[0].distance > 0.45) hasLowConfidence = true;

    const lines = results.map((r, i) => {
      const m = r.metadata;
      const score = (1 - r.distance).toFixed(3);
      let text = r.text;
      if (text.length > 1000) text = text.slice(0, 1000) + "\n... (截斷)";
      return `  #${i + 1} | ${m.file_path}:${m.start_line}-${m.end_line} | ${score} | ${m.language}\n${text}`;
    });

    allParts.push(`── Q${qi + 1}: "${query}" → ${results.length} 個結果\n${lines.join("\n\n")}`);
  }

  const header = `🔍 批次查詢: ${args.queries.length} 個 → collection ${collectionName}\n\n`;
  const warning = hasLowConfidence
    ? `⚠️ 部分查詢最佳結果 distance > 0.45，語意搜尋信心度低。建議改用 Grep 精確搜尋或 class_method_lookup 直接定位。\n\n`
    : "";
  return { content: [{ type: "text", text: header + warning + allParts.join("\n\n") }] };
}

// ── rag_status ─────────────────────────────────
async function handleStatus(client, args) {
  if (!args.project) {
    // 列出所有 collections
    const collections = await client.listCollections();

    if (collections.length === 0) {
      return {
        content: [
          {
            type: "text",
            text:
              "ChromaDB 已連線 ✅，但尚無任何 collection。\n" +
              "使用 rag_index 建立索引。",
          },
        ],
      };
    }

    const lines = [`ChromaDB 已連線 ✅ | ${collections.length} 個 collections：\n`];

    for (const col of collections) {
      const colName = col._name || col.name || String(col);
      try {
        const count = await col.count();
        lines.push(`  📦 ${colName} — ${count} 個切片`);
      } catch {
        lines.push(`  📦 ${colName} — (無法讀取)`);
      }
    }

    return { content: [{ type: "text", text: lines.join("\n") }] };
  }

  // 特定專案詳情
  const collectionName = `rag_${args.project}`;
  try {
    const collection = await getCollection(client, collectionName);
    const count = await collection.count();

    // 取得所有已索引檔案的 metadata（分頁拉取）
    const allMetadatas = [];
    const PAGE_SIZE = 5000;
    let offset = 0;
    let hasMore = true;
    while (hasMore) {
      const batch = await collection.get({
        limit: PAGE_SIZE,
        offset,
        include: ["metadatas"],
      });
      if (!batch.ids || batch.ids.length === 0) break;
      allMetadatas.push(...batch.metadatas);
      offset += batch.ids.length;
      if (batch.ids.length < PAGE_SIZE) hasMore = false;
    }

    // 統計
    const fileMap = new Map();
    for (const m of allMetadatas) {
      if (!fileMap.has(m.file_path)) {
        fileMap.set(m.file_path, {
          chunks: 0,
          language: m.language,
          indexed_at: m.indexed_at,
        });
      }
      const f = fileMap.get(m.file_path);
      f.chunks++;
      if (m.indexed_at > f.indexed_at) f.indexed_at = m.indexed_at;
    }

    // 依語言分組統計
    const langStats = {};
    for (const [, info] of fileMap) {
      langStats[info.language] = (langStats[info.language] || 0) + 1;
    }

    const lines = [
      `📦 Collection: ${collectionName}`,
      `   切片總數: ${count}`,
      `   檔案總數: ${fileMap.size}`,
      `   語言分佈: ${Object.entries(langStats).map(([k, v]) => `${k}(${v})`).join(", ")}`,
      "",
    ];

    // 最近索引的 10 個檔案
    const sorted = [...fileMap.entries()].sort(
      (a, b) => (b[1].indexed_at || "").localeCompare(a[1].indexed_at || "")
    );
    lines.push("   最近索引的檔案：");
    sorted.slice(0, 10).forEach(([fp, info]) => {
      const time = info.indexed_at
        ? new Date(info.indexed_at).toLocaleString("zh-TW")
        : "?";
      lines.push(`     ${fp} (${info.chunks} chunks, ${time})`);
    });
    if (sorted.length > 10) {
      lines.push(`     ...及其他 ${sorted.length - 10} 個檔案`);
    }

    return { content: [{ type: "text", text: lines.join("\n") }] };
  } catch (err) {
    if (err.message?.includes("does not exist")) {
      return {
        content: [
          {
            type: "text",
            text:
              `Collection ${collectionName} 不存在。\n` +
              `使用 rag_index 建立索引：rag_index { project: "${args.project}", paths: ["${args.project}/"] }`,
          },
        ],
      };
    }
    throw err;
  }
}
